version: '3'
services:
  server:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: autocomplete_server
    ports:
      - 3000:3000

  ui:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: autocomplete_ui
    ports:
      - 4200:80
    links:
      - server